### ISSUE TITLE
Creation of a bin module

### ISSUE THREAD

**Issue by ZwFink** [LadnerLab/PepSIRF#4]
A module should be created that allows for the binning (clustering) of peptides with scores that are similar to each other. Typically, the subjoin module will be used to specify samples that are negative controls. Bins would then be created from these samples, allowing the z-scores for a peptide to be calculated from the scores of the peptides it shares a bin with.

**Inputs**:
- A score matrix containing peptides and the count/score for each peptide in different samples.
- The 'rounding factor' for the scores parsed from the score matrix. Scores found in the matrix will be rounded to the nearest 1/10^x for a rounding factor x. For example, a rounding factor of 0 will result in rounding to the nearest integer, while a rounding factor of 1 will result in rounding to the nearest tenth.
- The minimum number of peptides a bin can contain. Any bin that would have fewer than this number of peptides will be joined with the next bin. 

**Output**:
- A file containing the bins, one line per bin. Each bin will be a tab-delimited list of the names of the peptides in the bin.

**Comment by jtladner** [comment]
Looks good. Please make sure that you have a mechanism to ensure that every peptide is assigned to a bin. The quick and easy solution I have used previously is to start the binning with the  peptides with the largest counts. This seemed to work because this part of the distribution is more sparse. But I am sure there are other ways to deal with this also.
