### ISSUE TITLE
Batch mode for deconv module

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#6]
Currently, separate calls need to be made to the deconv module for each sample. This module should be altered to allow samples to be processed in batches.

**Comment by ZwFink** [comment]
What if we abstract batching behavior into a separate module? Instead of having a batch mode for each of the modules, we can do something like **pep_sirf batch deconv ...**, **pep_sirf batch s_enrich**, etc. We'll have to take care about how batched inputs are handled, but it shouldn't be too difficult. 

Additionally, it may be good to have a pipeline module that takes the module name and a list of arguments to invoke the module with, one per line. It can then "call" each module in the order specified in the file, mapping the output of one module to the input of the next.

**Comment by jtladner** [comment]
I like the idea of the pipeline module. Once we finish the currently planned modules, let's set up a meeting to discuss how this would work. 

How exactly are you envisioning the batch module working? Would all of the normal arguments be specified to deconv, for example, but then an additional argument be specified to batch indicating all of the input files to run with those arguments? Could get complicated for modules that require several different input files...

**Comment by jtladner** [comment]
The alternative that I see if to make batch mode the only mode for deconv. If we set it up to run multiple samples (when provided), the user can always just specify a single sample to recreate the current functionality.

**Comment by ZwFink** [comment]
For modules with multiple input files, we could create a file like:
```
arg1:file1,file2.file3
arg2:file1,file2,file3
output:out_1,out_2,out_3
```

Specifying three different runs within a batch run. Then, the specified module will run three times, using the arguments in a single column for a run. Unspecified arguments will take their default values.

But, this file may be quite tedious to make and is likely prone to error by the user. So it's probably best to just let a module take care of its batching when necessary

**Comment by jtladner** [comment]
Yes, I see that it could be possible. However, I'm also not sure how many modules would actually need a batch mode, since this is essentially the default behavior in most cases, given that a full matrix is processed. 

Let's plan for now to just adjust deconv to support batch processing by default.
