### ISSUE TITLE
Subjoin - Renaming bug

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#99]
When using subjoin, it's possible to rename samples in the output file by providing a second column in the names input file. However, IF the new name matches the name of a sample in the input file, that sample's column is included in the output file. What should happen in these cases is that the column of data matching the name in the first column should be grabbed, but the name should be changed to the name in the second column for the output file.

**Comment by vidalrmartinez** [comment]
My solution for this was to create an additional method for the matrix class used to contain the sample and peptide names and scores. This will work for both a run that modifies peptide names and a run modifying sample names. The new method clears all names currently used and emplaces the desired names for output in the same order as the original. An ordered list is used to obtain the desired output names (whether they are replaced by a new name or unchanged) in an order dictated by the matrix building. The simple way to look at this is: each name has a correlating index and this is mirrored by an external ordered list that maintains the indexing order for each name. Before implemented in the matrix, the list is verified to make sure there are no duplicates. This has been tested with various combinations of namelist files (tab delimited file provided as the second in the pair for input with the score matrix(s)). If no namelist file is provided, this process described is skipped, because there is no need to handle name replacements or duplicate names. This will be closed with the release of v1.3.6.
